language: php

php:
 - 7.0.15

branches:
 - master

before_script:
 - cd /home/travis/build/
 - phpenv config-rm xdebug.ini
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.2
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0
 - git clone --recursive --branch=master https://github.com/pmmp/PocketMine-MP.git
 - mkdir -p PocketMine-MP/plugins/TopVoter-src
 - cp -rf SalmonDE/TopVoter/src PocketMine-MP/plugins/TopVoter-src
 - cp -rf SalmonDE/TopVoter/resources PocketMine-MP/plugins/TopVoter-src
 - cp -rf SalmonDE/TopVoter/plugin.yml PocketMine-MP/plugins/TopVoter-src
 - cp -rf SalmonDE/TopVoter/LICENSE PocketMine-MP/plugins/TopVoter-src
 - cp -rf SalmonDE/TopVoter/build.php PocketMine-MP/
 - cd PocketMine-MP/plugins/
 - wget -O DevTools.phar https://github.com/pmmp/PocketMine-DevTools/releases/download/v1.11.2/PocketMine-DevTools_v1.11.2.phar
 - cd /home/travis/build/PocketMine-MP

script:
 - php build.php

deploy:
  provider: releases
  api_key: "$traviskey"
  file: "/home/travis/build/PocketMine-MP/plugins/DevTools/TopVoter.phar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: false

notifications:
 email: false
